name: osm_opening_hours
description: Validation and canonical formatting for OpenStreetMap opening_hours tag values
version: 1.0.0
repository: https://github.com/matisiekpl/osm-opening-hours

environment:
  sdk: ^3.11.4

dependencies:
  antlr4: ^4.13.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
